### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by Matt-Lepley** [rochebox/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by rochebox** [comment]
Hi Matt, 
Thanks for taking a look,  I googled the issue and it seems from the bootstrap documentation and looking at others with a similar issue, it would be good to include  the meta tag:
<meta name="viewport" content="width=device-width, initial-scale=1">

I put it in applications.html.erb!

![splurty riff-it on the phone w meta](https://cloud.githubusercontent.com/assets/4305309/11479361/8f1a7d78-975f-11e5-924d-64884cba6634.png)

I git committed it and reloaded heroku ---->  Looks much better!!

Tried to include a photo here, but I think its better now!

Thanks, 
Chris

**Comment by rochebox** [comment]
I think its closed now?  yes,  Let me know!

**Comment by Matt-Lepley** [comment]
Yup! Thumbs up, great job!
